### ISSUE TITLE
different result of transformation each time on same content

### ISSUE THREAD

**Issue by mainpart** [qntfy/kazaam#116]
I have an example of complex transformation where kazaam demonstrates inconsistent behaviour. I ran https://go.dev/play/p/yVCIkyphvNJ several times and each time it drops section, returning them to correct positions, loses them again... on the same ruleset and input data.

I guess it's because of random order somewhere inside app and the only way i can think of it is a map order of which is undetermined.

You can run code several times too and watch yourself that event.payload.order.delivery: { expectedTo:.., expectedFrom:...} section either in place, partially in place with one of key-value pair or completely lost. All these outcome are on static data with same input and same output

**Comment by mainpart** [comment]
i've made test that runs 1000 times and measures existance of key vs non existance

https://go.dev/play/p/mDwJoep9JfJ

```golang
func main() {
	var exists, notexists int
	kazaamConfig := kazaam.NewDefaultConfig()
	k, _ := kazaam.New(specStringChange, kazaamConfig)
	for i := 1; i < 1000; i++ {
		out, _ := k.TransformJSONStringToString(smRequest)
		value := gjson.Get(out, "event.payload.order.delivery")
		if value.Exists() {
			exists++
		} else {
			notexists++
		}

	}
	fmt.Println(exists, "  ", notexists)
}

```

Aprox 700 times key exists in outputted structure and aprox 300 times it missing. 

### What am i missing?

**Comment by thomas-tharp** [comment]
Hi,

You are correct that in Go, map order is non-deterministic. That means, in your final shift spec, sometimes `"event.payload": "payload"` will be evaluated after the lines that set `event.payload.order` fields, effectively erasing those fields.

If you set those in your block where you set the rest of the payload fields, you can avoid this. See lines 81-83 in this working example: https://go.dev/play/p/Yfsxv5t-SBA

Let me know if that fixes your issue, or if there's something else you see going wrong.

Thanks,

Tom

**Comment by mainpart** [comment]
i'm trying to shift the shift section further and came up with this last section https://go.dev/play/p/v7i897TSECR
```
  {
    "operation": "shift",
    "spec": {
      "order.changed": "orderLinesChanged",
      "order.delivery.expectedFrom": "expectedFrom",
      "order.delivery.expectedTo": "expectedTo"
    },
    "over": "event.payload"
  }
```

it's perfectly fine with json schema and it happens before in spec so i guess it should be valid but kazaam parser produces error:

```
panic: Value is array, but can't find closing ']' symbol
```

if i remove over section it parses fine. Error happens here:
```
			_, err = jsonparser.ArrayEach(data, func(value []byte, dataType jsonparser.ValueType, offset int, err error) {
				transformedDataList = append(transformedDataList, transform.HandleUnquotedStrings(value, dataType))
			}, overKeys...)
```

**Comment by thomas-tharp** [comment]
`event.payload` is not an array in that example, just an object, so you don't need the `over` specifier.
