### ISSUE TITLE
Check parsing of long ints

### ISSUE THREAD

**Issue by yelskiy** [qntfy/kazaam#18]
Ensure that json that is kazaam'd doesn't modify how long integers are handled. 

See: http://stackoverflow.com/questions/22343083/json-marshaling-with-long-numbers-in-golang-gives-floating-point-number
https://go-review.googlesource.com/#/c/30371/

JSON decoding may need to change to something along these lines:
```go
        var src map[string]interface{}
        decoder := json.NewDecoder(bytes.NewReader(payload))
        decoder.UseNumber()
        err := decoder.Decode(&src)
```

**Comment by ryanleary** [comment]
@yelskiy this ended up being ok?

**Comment by yelskiy** [comment]
@ryanleary yes. this can be closed

**Comment by ryanleary** [comment]
Closing as not reproducible.
