### ISSUE TITLE
When Importing i get the error cannot use transform.Pass (type func(*transform.Config, []byte) ([]byte, error)) as type TransformFunc in map value for all of the transforms 

### ISSUE THREAD

**Issue by ALynch11** [qntfy/kazaam#41]
im not really sure why the simplejson type is not being interpreted correctly

**Comment by ryanleary** [comment]
Which version of kazaam are you using? We recently pushed v3 to master which no longer uses simplejson for tremendous speedups and reduction in memory usage/allocations.

**Comment by ALynch11** [comment]
I was using v2. It worked fine when i switched to the new version. Thanks
