### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by chilland** [qntfy/kazaam#45]
Tests often fail due to the random order of JSON keys. This may be due to golang's randomized map iteration. All of the tests should be reviewed to ensurer they account for this fact and that `go test` doesn't fail at random.

**Comment by Nearhan** [comment]
What were you thinking?
Implementing a helper that can compare strings?

**Comment by ryanleary** [comment]
I wonder if we could somehow easily leverage our old friend simplejson or jsonparser to write a recursive jsonEqual method?

**Comment by chilland** [comment]
I think we can just use `json.Unmarshal` and `reflect.DeepEqual` right?

**Comment by chilland** [comment]
Closed by #48
