### ISSUE TITLE
Trouble loading specificationUnable to load Kazaam specification file: json: cannot unmarshal object into Go value of type kazaam.specs

### ISSUE THREAD

**Issue by zolvaczi** [qntfy/kazaam#59]
Whichever transformation spec example I am trying with the command line tool, I get this error.

**Comment by zolvaczi** [comment]
# ./kazaam -verbose -in concat-in.json -spec concat-op.json
2017/09/18 13:31:52 Trouble loading specificationUnable to load Kazaam specification file: json: cannot unmarshal object into Go value of type kazaam.specs

# cat concat-op.json
{
    "operation": "concat",
    "spec": {
        "sources": [{
            "value": "TEST"
        }, {
            "path": "a.timestamp"
        }],
        "targetPath": "a.timestamp",
        "delim": ","
    }
}

**Comment by zolvaczi** [comment]
Need to be in a JSON array. Sorry!

**Comment by ryanleary** [comment]
Thanks for filing the issue.

I'm going to reopen this so that we:
a) improve the documentation,
b) perhaps add support for single spec.
