### ISSUE TITLE
Add string concatenation operation

### ISSUE THREAD

**Issue by chilland** [qntfy/kazaam#6]
It would be nice to be able to specify a string to be concatenated to the contents of a given field. This could potentially be extended to regex more generally.

**Comment by germanvazquez-rfk** [comment]
yeah, I am investigating this lib and probably be using it.
wonder if it is in active dev.

**Comment by ryanleary** [comment]
It is still actively developed. Feel free to file issues or PRs.

**Comment by ryanleary** [comment]
How about concatenation of multiple fields? separators?

**Comment by ryanleary** [comment]
Closed by #16.
