### ISSUE TITLE
Issue when installing kazaam v3

### ISSUE THREAD

**Issue by mammenj** [qntfy/kazaam#69]
when executing in go version `go1.9 linux/amd64`
`go get gopkg.in/qntfy/kazaam.v3`
below output in command line
```
> # github.com/qntfy/kazaam/transform
> go-workspace/src/github.com/qntfy/kazaam/transform/uuid.go:33:18: multiple-value uuid.NewV4() in single-value context
```

**Comment by ryanleary** [comment]
Thanks for the report. Looks like the github.com/satori/go.uuid changed their `New` signature without increasing the major version number breaking this build. Our glide configuration, however, is locked to the correct version, so if you check out kazaam from git, run `glide up`, and then build yourself it should work. 

In the meantime we'll get kazaam updated to use the new, changed signatures.

**Comment by ryanleary** [comment]
This bit some other people as well: https://github.com/satori/go.uuid/issues/66
