### ISSUE TITLE
Error on "go get github.com/qntfy/kazaam"

### ISSUE THREAD

**Issue by kabukky** [qntfy/kazaam#85]
Hi,

in the master branch of `github.com/satori/go.uuid`, `uuid.NewV4()` returns an error. In the pinned version `v1.2.0`, that function does not return an error. But since `go get` always pulls the master branch, `github.com/qntfy/kazaam` is not `go get`-able at the moment.

Here's the error:
`../github.com/qntfy/kazaam/transform/uuid.go:33:18: multiple-value uuid.NewV4() in single-value contex`

This problem was introduced with PR #76 .

**Comment by chilland** [comment]
Thanks for pointing this out. Looks like `github.com/satori/go.uuid` is no longer maintained has some critical bugs. We'll get this fixed ASAP.
