### ISSUE TITLE
README uses wrong path in Usage section

### ISSUE THREAD

**Issue by tuptaker** [qntfy/kazaam#90]
Under the "Usage" section of the readme, the reader is instructed to cd into the Kazaam directory after running go get:
`cd $GOPATH/src/gopkg.in/qntfy.kazaam.v3/kazaam`

But this is the wrong path. The correct command with the correct path is:
`cd $GOPATH/src/gopkg.in/qntfy/kazaam.v3/kazaam`

**Comment by JoshKCarroll** [comment]
Fixed by #91, thank you for reporting and taking initiative to fix!

**Comment by tuptaker** [comment]
My pleasure, glad I could help!
