### ISSUE TITLE
Documentation regarding RegisterTransform

### ISSUE THREAD

**Issue by subcon42** [qntfy/kazaam#92]
Using: `go version go1.11.1 linux/amd64` in a known-working environment.

On the page/section: https://godoc.org/gopkg.in/qntfy/kazaam.v3#Config.RegisterTransform

The example block shown, when copied and used **verbatim**, produces:

```
cannot use func literal (type func(*"gopkg.in/qntfy/kazaam.v3/transform".Config, []byte) ([]byte, error)) as type kazaam.TransformFunc in argument to kc.RegisterTransform
```

**Comment by subcon42** [comment]
FWIW, this does not seem to happen when using "github.com/qntfy/kazaam" in ones `import (...)` statement(s), as opposed to "gopkg.in/qntfy/kazaam.v3".   This might confuse people, since ones search results on the web may vary, and lead users to one over the other.  This is what happened to me.

Given the documentation itself is accurate, then the title of this issue may be worthy of a rename, not sure.  But something was fishy for certain.

**Comment by cgarvis** [comment]
I just ran into this.  Key is to switch your import from `gopkg.in` with `v3 to a plain `github.com` import.
